### ISSUE TITLE
Problems with some waterlogged blocks

### ISSUE THREAD

**Issue by roket333** [erich666/Mineways#50] opened 2020-01-01 23:32 UTC
![image](https://user-images.githubusercontent.com/5241048/71647366-14ebfe80-2cb3-11ea-816c-cc4c393e5936.png)
In some cases, faces of waterlogged blocks, like the upside down stairs to the right, are incorrectly culled. This does not happen with non-waterlogged blocks or if the block above them is not water or not a waterlogged block. Waterlogged chests also have an issue where they are not waterlogged on export and their lock is misplaced.

**Comment by erich666** [comment] 2020-01-02 16:32
Thanks (especially for the image), and I have to admit to not really understanding "waterlogged" fully and what it should mean for Mineways export. I've been kind of ignoring the attribute, since it says on https://minecraft.gamepedia.com/Waterlogging "In Java Edition, certain blocks have a waterlogged block state that can be true or false. This is a temporary solution; a full separation of blocks and fluids is planned." It seems like this is probably wrong, given that "waterlogged" has now been around awhile.

I'll try to get to it, but given that this is the first bug request on waterlogged in the year and a half since the feature was added to Minecraft (and Mineways), I'm not feeling a strong sense of urgency. I'll at least start by seeing if I can reproduce the upside-down step problem.

**Comment by erich666** [comment] 2020-02-02 15:48
The chest problem is now fixed in version 7.10, as is the disappearing faces problem (which was happening with slabs and stairs regardless of whether they were waterlogged or not - they just had to be next to water).

**Closed by erich666** 2020-02-02 15:48 UTC
Labels: bug
