### ISSUE TITLE
OBJ file fails to import in Blender 2.90.1

### ISSUE THREAD

**Issue by Mhowser** [erich666/Mineways#73] opened 2021-01-18 10:42 UTC
Hey there, I am trying to import the OBJ file that I exported using Mineways v8.01a. I am using WINE v6.0 on Ubuntu 18.04 BTW. This is the error I get from blender 
```
(  0.0001 sec |   0.0001 sec) Importing OBJ '/home/cosmocrat/Downloads/minecuberender.obj'...
  (  0.0009 sec |   0.0001 sec) Parsing OBJ file...
    (  0.0577 sec |   0.0562 sec) Done, loading materials and images...
WARNING: '/home/cosmocrat/Downloads/minecuberender.obj':b'interpolateMode NEAREST_MAGNIFICATION_TRILINEAR_MIPMAP_MINIFICATION' (ignored)
WARNING: '/home/cosmocrat/Downloads/minecuberender.obj':b'interpolateMode NEAREST_MAGNIFICATION_TRILINEAR_MIPMAP_MINIFICATION' (ignored)
WARNING: '/home/cosmocrat/Downloads/minecuberender.obj':b'interpolateMode NEAREST_MAGNIFICATION_TRILINEAR_MIPMAP_MINIFICATION' (ignored)
WARNING: '/home/cosmocrat/Downloads/minecuberender.obj':b'interpolateMode NEAREST_MAGNIFICATION_TRILINEAR_MIPMAP_MINIFICATION' (ignored)
WARNING: '/home/cosmocrat/Downloads/minecuberender.obj':b'interpolateMode NEAREST_MAGNIFICATION_TRILINEAR_MIPMAP_MINIFICATION' (ignored)


Traceback (most recent call last):
  File "/usr/share/blender/2.90/scripts/addons/io_scene_obj/__init__.py", line 146, in execute
    return import_obj.load(context, **keywords)
  File "/usr/share/blender/2.90/scripts/addons/io_scene_obj/import_obj.py", line 1246, in load
    use_image_search, float_func)
  File "/usr/share/blender/2.90/scripts/addons/io_scene_obj/import_obj.py", line 361, in create_materials
    context_mat_wrap.emission_strength = 1.0
AttributeError: 'PrincipledBSDFWrapper' object has no attribute 'emission_strength'
```
Here is the OBJ file I am trying to import [minecuberender.obj.txt](https://github.com/erich666/Mineways/files/5829602/minecuberender.obj.txt) (Remove `.txt`)

Please let me know if you need additional info.

**Comment by erich666** [comment] 2021-01-18 15:30
Interesting that you get a warning about those lines. Those are indeed non-standard lines I add to the OBJ export. They are so that the textures appear blocky, in Minecraft style, when viewed in the G3D viewer that I use and suggest for others.

Basically, ignore the warnings, and I'm glad to hear that Belnder ignores them, too. I might change Mineways to export these "nearest neighbor" hints only when the custom material is exported. I'm hoping to have a minor update to Mineways this week.

Thanks for reporting this problem.

**Comment by erich666** [comment] 2021-01-18 15:30
Interesting that you get a warning about those lines. Those are indeed
non-standard lines I add to the OBJ export. They are so that the textures
appear blocky, in Minecraft style, when viewed in the G3D viewer that I use
and suggest for others.

Basically, ignore the warnings, and I'm glad to hear that Belnder ignores
them, too. I might change Mineways to export these "nearest neighbor" hints
only when the custom material is exported. I'm hoping to have a minor
update to Mineways this week.

Thanks for reporting this problem.

**Comment by Mhowser** [comment] 2021-01-18 19:57
Your welcome! Which lines can I remove so that blender will import it?

**Comment by erich666** [comment] 2021-01-20 00:19
Aha, it's not the NEAREST_MAGNIFICATION_TRILINEAR_MIPMAP_MINIFICATION lines that are causing you problems. Note that these give just warnings, not errors.

The error I see in your listing is:

> AttributeError: 'PrincipledBSDFWrapper' object has no attribute 'emission_strength'

I don't know what that error is from, but it's not from Mineways, from what I can tell. I tested by downloading Blender 2.91.0 and importing an OBJ of some blocks in a world from the latest version of Mineways. I didn't get any errors.

If you are still getting errors (and how do you see your error log? I don't know how to do that in Blender), please zip up your export files from Mineways and send them to me. I can then try to reproduce the error here and debug it. I'm at erich@acm.org

**Comment by erich666** [comment] 2021-01-30 15:06
Ping on this one, Mhowser. Can you give me more details, since I cannot reproduce the problem here with Blender 2.91.0. Perhaps you could attach a zip file of the OBJ, MTL, and PNGs exported from Mineways that are giving you problems? Without a debug case I cannot fix this bug, and so will close it.

**Comment by Mhowser** [comment] 2021-01-30 17:06
Sorry I didnt see notifications for this issue on my main email.
Anyway, here is the Zip file containing all that you asked for 
[test1.obj.zip](https://github.com/erich666/Mineways/files/5898345/test1.obj.zip) 
And here is a debug log from Mineways
[mineways_debug.log](https://github.com/erich666/Mineways/files/5898346/mineways_debug.log)
I was able to see the error made by blender by starting it from a Terminal.

**Comment by Mhowser** [comment] 2021-01-30 17:14
WAIT A SECOND. I just realized you were using Blender version 2.91.0. I was using 2.90.1. So I tried importing the obj in 2.91 and it works! 
![image](https://user-images.githubusercontent.com/24195572/106363129-7da11280-62db-11eb-8b87-06218994eb08.png)

So for some reason this doesnt work on the older 2.90 version.

**Comment by erich666** [comment] 2021-01-30 17:18
Excellent! I'm glad they fixed it on the Blender side. Whew, thanks for following up.

Also, note there's a new version of Mineways out, 8.02, which has a few useful fixes.

**Closed by erich666** 2021-01-30 17:18 UTC
