### ISSUE TITLE
"Grass" and "Flower" wrong position

### ISSUE THREAD

**Issue by vuiquahuhu** [erich666/Mineways#45] opened 2019-06-25 06:26 UTC
mineways version : 7.02

1. "Grass" and "Flower" is wrong position . It will penetrate the mesh of the beside block. When i bake AO map, the mesh intersection will cause black.

2. Plants ( Cactus,Grass,Flower... ) through the ground mesh. It also causes problems when bake ambient occlusion map. I think you should put them a few millimeter off the ground.

![error](https://user-images.githubusercontent.com/48952198/60074037-34c2c880-974c-11e9-979f-e39e7d6482d3.png)
![error2](https://user-images.githubusercontent.com/48952198/60099735-766e6600-9782-11e9-9b9d-6aae42232187.png)
![error1](https://user-images.githubusercontent.com/48952198/60074316-cfbba280-974c-11e9-801f-89ee120f24ab.png)

![ezgif-1-22c80c3d7e75](https://user-images.githubusercontent.com/48952198/60099691-6060a580-9782-11e9-8070-65f8320d3be7.gif)
![ezgif-1-3281d500805f](https://user-images.githubusercontent.com/48952198/60100289-9fdbc180-9783-11e9-86c4-826bc7be9dbc.gif)

**Comment by erich666** [comment] 2019-06-25 11:01
Thanks for reporting this. I am on vacation for two weeks but I’ll check it out when I get home.

**Comment by vuiquahuhu** [comment] 2019-06-25 13:04
Thank you for the quick reply! I have also updated my error report in more detail.

**Comment by erich666** [comment] 2019-07-05 17:46
Thanks for the detailed report (images are always appreciated). I'm afraid this falls in the category of "there's a problem with your baker." The bottom of the grass billboards do not go below the ground, rather they exactly touch the ground. This is the same behavior as Minecraft, AFAIK, so Mineways emulates this properly.

![tall_grass](https://user-images.githubusercontent.com/803995/60737854-2d5ca580-9f2a-11e9-84d7-7d59e6826f06.jpg)

To have the grass appear a bit above the ground, I suggest selecting the tall grass elements and then moving them in your modeler, manually.

Not having the grass billboards interpenetrate blocks next to them is a tougher one, and I'm afraid I have no good answer for that. If it were me, I'd write a Perl or Python script that went through the OBJ file and modified the vertices labeled as being part of the tall grass, pulling them in a bit. A pain to write: you have to find the section of faces with:

> g Grass
> usemtl Grass

and then modify the vertices associated with those faces appropriately.

I hope you'll understand why I don't want to try to do this within Mineways itself. This is a specialized need that you are requesting and putting such code into Mineways itself would be a lot of additional complexity that would help only a very few users. I can imagine doing so with scripting, some way of identifying content and then applying some given transformation matrix to it. If this was a common thing people wanted to do, I'd probably add it, but you're the first to ever ask for it.

Long and short, for now, no. I'll leave this issue as "open" in case others want to comment.

**Comment by erich666** [comment] 2019-07-05 17:52
I should also note that Minecraft itself lets flowers interpenetrate blocks, for good or ill.

![2019-07-05_13 51 04](https://user-images.githubusercontent.com/803995/60738362-18811180-9f2c-11e9-8ada-0524eb9087ec.png)

**Comment by erich666** [comment] 2019-07-05 17:55
Oh, one thing I _could_ do is to add (yet another) export option, "turn off wobble" for the flowers, etc. Let me know if that would be a help - I can probably stuff it in there somewhere... I won't be adding a "move the flowers up a tad" option, though, as that seems super-specialized (and how much is "a tad"? It will vary for users).

**Comment by vuiquahuhu** [comment] 2019-07-06 01:56
I checked the grass in the game. This is an bug and Mojang is fixing it (https://bugs.mojang.com/browse/MC-610).
Sorry for losing your time because I didn't check in the game. Thank you again for a great software!

**Comment by erich666** [comment] 2019-07-06 19:20
Thanks, and that bug you list https://bugs.mojang.com/browse/MC-610 shows
grass and flowers being generated on top of blocks where they shouldn't be
generated, e.g., on top of cobblestones or water. This doesn't seem to have
anything to do with the "wobble" in the location of the grass, etc., within
the block itself; that's not a bug, AFAIK. So, I'll keep the wobble factor
going (though my wobble equation is different than Minecraft's, which I
don't know).

As far as your baking software goes, check whether it has an "epsilon"
fudge factor in it. A good baker should have some sort of "move along the
ray's direction to a location a tiny distance away from the ray's origin
before recording any intersections" control, otherwise there's always a
risk that an adjoining polygon will get hit by the test ray at a distance
of 0.000001 along the ray or similar, causing a false shadowing. What
baking software are you using, if I may ask?

**Comment by vuiquahuhu** [comment] 2019-07-07 23:45
I baked the AO map with Blender (Cycles bake) and these are all options available in the grill section. 

![k](https://user-images.githubusercontent.com/48952198/60775292-0204d100-a14b-11e9-8d70-d35bbd81bd54.png)


I see an "Ray Distance" option. I do not use the "Ray Distance" option, because I see people not using it (I see instructions on the internet).Is it something you're talking about? (Sorry, I don't know English. I use Google translate)

**Comment by erich666** [comment] 2019-07-08 01:31
It sounds like Ray Distance is something you would want to set to something
small, from reading this:
https://blender.stackexchange.com/questions/76416/how-to-bake-normal-map-if-the-models-intersect


Assuming each Minecraft block is 1 meter, I would try 0.01m as a start.
I'll be interested to hear if that works for you. You might even be able to
solve the "plant pokes into the side of the neighboring block" problem by
giving a larger start distance.

It's quite common to start the ray some distance from the origin; I even
coauthored a basic article about it this year - see figure 2-3:
https://link.springer.com/chapter/10.1007/978-1-4842-4427-2_2

**Comment by vuiquahuhu** [comment] 2019-07-08 06:58
I have read that article (and I also read almost all other tutorials). The article you are talking about is how to bake Normal Map and not AO map. When baking normal map, I still use "Ray Distance" and there is no problem.
In the blender the "Ray Distance" option only works when select 2 objects (eg "high poly object" and "low poly object" - just like when baking Normal map). When baking AO map I only have one object so the "Ray Distance" option will not work.

**Comment by erich666** [comment] 2019-07-08 15:08
Interesting that AO's ray distance is not the same sort of thing. I guess
the answer is to use Blender and manually shift all grass, flowers, etc.
upwards by some tiny amount, e.g. 0.01 meters. You could probably write a
script to do this.

**Comment by vuiquahuhu** [comment] 2019-07-08 16:23
I will try to do that. Thank you very much !!!

**Comment by erich666** [comment] 2019-12-21 18:12
Looking over the issues, can I close this one, @vuiquahuhu ? Or is there something more to be done on my end?

**Comment by vuiquahuhu** [comment] 2019-12-22 03:05
This error has not been resolved by Mojang, so I think you should not close this topic.

**Comment by erich666** [comment] 2019-12-22 15:03
> This error has not been resolved by Mojang, so I think you should not close this topic.

An interesting point, but I don't expect Mojang to ever fix this, right? It's how they like it. Anyway, they're certainly not going to look at this repo and notice this "bug." Basically, it's not a bug in Mineways, it's a case of "garbage in, garbage out."

That said, I might provide an option of "no randomness for plants," so that they don't jitter their positions at all. Would this be what you want? Basically, I want you to precisely sum up what you think is the error, and what you think the fix should be.

**Comment by vuiquahuhu** [comment] 2019-12-25 03:22
Sorry, because I don't know English, it's difficult to talk to you (I use google translate). I don't want you to close this topic because I am afraid that someone will have this problem and reopen a new topic. However, you can close the topic and display warn of problems that may occur when a user export a map :)

**Comment by erich666** [comment] 2019-12-26 15:17
OK, marking as "wontfix," since it is working as intended.

**Comment by erich666** [comment] 2020-08-26 19:39
Closing this issue, since it's "wontfix" - the Mojang bug you mention, https://bugs.mojang.com/browse/MC-610, is a bug with placing grass in the wrong places; it doesn't have anything to do with the wobble or height problems mentioned here.

**Closed by erich666** 2020-08-26 19:39 UTC
Labels: enhancement, wontfix
