### ISSUE TITLE
Problem Exporting (PNG error: failed to open file for writing)

### ISSUE THREAD

**Issue by Ginoskie** [erich666/Mineways#66] opened 2020-10-27 12:33 UTC
![image](https://user-images.githubusercontent.com/73532608/97298031-cfc23a00-188d-11eb-9eaf-fd2245ac4125.png)
![image](https://user-images.githubusercontent.com/73532608/97298079-e4063700-188d-11eb-9ef4-23f51cf62799.png)

It does not export the textures of the map (or the png files). The only files I get after exporting are the .mtl and .obj files

**Comment by erich666** [comment] 2020-10-27 13:53
Hmmm, that's odd, I haven't seen it before, and I don't have any great ideas. Were you using a special terrain set, or just had it doing default terrain? Are you out of disk space (unlikely, I know)? Try maybe saving to c:\temp (make the directory first, of course) to check that it's not a file path name problem. Anything you find is appreciated - I'd like to fix this, or at least understand the cause better and warn users.

**Comment by mrxbox98** [comment] 2020-10-29 23:32
I also had this problem using a custom world I had, I will try it with a generated world and see if the error still happens.

**Comment by mrxbox98** [comment] 2020-10-29 23:47
> I also had this problem using a custom world I had, I will try it with a generated world and see if the error still happens.

I just checked and it also happens for a normal world.

**Comment by erich666** [comment] 2020-10-30 13:23
Good to know @mrxbox98 . Unfortunately, I cannot reproduce this problem here, which means I cannot fix it. Could you please experiment a bit and see if there's anything that makes the problem happen, or not happen? For example:

- Try exporting a single block.
- Try exporting the model to c:\temp, like I mention above
- Try exporting using the "Export tiles for textures to directory" option
- Try "Export no materials" option - this should write no PNG files at all, so should work. Does it?
- Make sure to use simple file names, like "mytest" - nothing clever

With five minutes of testing (if that), you might find what the problem is. I can then possibly fix it, if I know what the problem is.

**Comment by erich666** [comment] 2021-01-30 15:12
@mrxbox98 do you have any additional information on this one? Did you give it a test with the ideas I give above? If I can't get more information, I can't reproduce the bug and so will have to close this issue.

The possibly-good news is that I did update the lodepng library I use, which had a number of code fixes in it. These might help solve your problem, though I'm a bit doubtful - it sounds more like a path problem than PNG writing per se. Still, you might give [version 8.02](http://mineways.com), the latest Mineways, a try and see. Anyway, if I don't hear back in a month I'll have to close this one as unreproducible.

**Comment by Ginoskie** [comment] 2021-01-31 11:07
I got it fixed with your solution. I just saved it in a different path folder and it worked. Thanks!
    On Saturday, January 30, 2021, 11:13:08 PM GMT+8, Eric Haines <notifications@github.com> wrote:  
 
 


@mrxbox98 do you have any additional information on this one? Did you give it a test with the ideas I give above? If I can't get more information, I can't reproduce the bug and so will have to close this issue.

The possibly-good news is that I did update the lodepng library I use, which had a number of code fixes in it. These might help solve your problem, though I'm a bit doubtful - it sounds more like a path problem than PNG writing per se. Still, you might give version 8.02, the latest Mineways, a try and see. Anyway, if I don't hear back in a month I'll have to close this one as unreproducible.

**Comment by erich666** [comment] 2021-01-31 17:26
Perfect, thanks for letting me know, and I've updated [the downloads page](http://www.realtimerendering.com/erich/minecraft/public/mineways/downloads.html) to note this problem.

**Closed by erich666** 2021-01-31 17:26 UTC
