### ISSUE TITLE
[OBJ export] Bottom face of copper ore block is flipped vertically

### ISSUE THREAD

**Issue by kazarmy** [erich666/Mineways#111] opened 2023-07-19 04:54 UTC
As shown here:

![Minecraft](https://github.com/erich666/Mineways/assets/12002672/5e8f59da-ff3f-4d81-ab44-e0bec8a0dbb0)
(KappaPT P16b shader, Minecraft 1.19.4)

![Blender](https://github.com/erich666/Mineways/assets/12002672/45f4b9a8-08e3-43d6-a55b-ed2a64ec9881)
(Blender 3.5.1, Mineways 11.00)

in an exported OBJ, the bottom face of the copper block above is flipped vertically. Since it is a flip, this isn't due to random block rotation. I fixed this in Blender by flipping vertically all bottom faces but I thought this would be better fixed at the source.

Btw, here's a final render:

![BlendLuxCore](https://github.com/erich666/Mineways/assets/12002672/fc03b5d1-112e-48d7-b0dd-ea236d7dc7b4)
(BlendLuxCore 7deee59, Blender 3.5.1, Mineways 10.15)

**Comment by erich666** [comment] 2023-08-29 19:34
This used to be a feature, not a bug. Once upon a time, Minecraft itself would mirror the bottoms like this, to match the tops. Testing today with the Debug World and a custom texture pack, I see it's no longer doing this. I don't know what version of Minecraft this changed in, but I'm fixing Mineways to match 1.20.1. I've made the change, it'll be in the next version.

You can download a beta executable with this fix at https://www.realtimerendering.com/erich/minecraft/public/mineways/downloads/Mineways_11.02beta_no_mirroring.zip - let me know how it goes. It looked good on my end, here's an export from Debug World, with a custom texture pack applying an "R" in the lower left corner, for testing:
![mirror_fix](https://github.com/erich666/Mineways/assets/803995/b7408d73-7c4e-44f3-b076-5c75e2688924)

**Comment by kazarmy** [comment] 2023-08-30 04:31
> ... here's an export from Debug World, with my custom texture pack applying an "R" in the lower left corner ...

Hmm apparently the stairs did not get the memo ... or maybe they did and it's the copper ore column that didn't (imo it looks nicer if the "R" is not flipped).

> ... let me know how it goes

![Copper ore bottom face](https://github.com/erich666/Mineways/assets/12002672/4d195459-714b-4b76-a6fc-66ce27f085d2)

I see from da96913d60a32f91a1e088c1059e619801d2132e that you have turned off bottom face reversal, but from the above it appears the bottom face actually needs to be flipped twice on both axes, or 3,4,1,2 instead of 2,1,4,3 or no reversal at all.

**Comment by erich666** [comment] 2023-08-30 14:15
Good catch! Me, I was happy I just got the R's to no longer be mirrored. I should have checked orientation on the faces more carefully - there's a separate code path for partial blocks like steps (which were fine, like you say) vs. full blocks. A quick change on full blocks and voila:

![this_time_for_sure](https://github.com/erich666/Mineways/assets/803995/6e885d6f-7963-4b4e-9f9f-48bb6400003b)

[This time for sure](https://youtu.be/yIBdVkJ9L-k?list=RDyIBdVkJ9L-k&t=62). Please give this new beta a try: https://www.realtimerendering.com/erich/minecraft/public/mineways/downloads/Mineways_11.02beta_fix2.zip

**Comment by kazarmy** [comment] 2023-08-30 14:48
> [This time for sure](https://youtu.be/yIBdVkJ9L-k?list=RDyIBdVkJ9L-k&t=62).

yep, it can a bit tricky to pull rabbits out of hats, but the sense of relief one gets when it happens ... priceless! 

> Please give this new beta a try:

![Copper ore bottom face (2nd time)](https://github.com/erich666/Mineways/assets/12002672/27a25b53-f3bf-4368-9bdc-1d144c1213ae)

Looks good to me.

**Comment by erich666** [comment] 2023-08-30 15:38
Fast response - you're the best! Thanks for the reality check.

And of course I went down the rabbit hole on this one, checking other blocks. Logs that are oriented sideways are also wrong (now fixed). And I just noticed a bug with sunflower heads... Wish me luck :)

**Comment by erich666** [comment] 2023-08-30 20:24
Also fixed bone blocks and observers, checked kelp. I suspect I should check over every detailed block - I know pistons are off - but good enough for now. I'll leave this issue open as a reminder to do this someday, block by block.

**Comment by kazarmy** [comment] 2023-08-30 23:36
> Fast response - you're the best!

It just so happened that I was at my keyboard with time to spare when your reply came in though :sweat_smile: ... I generally will try to respond within 24 hours, earlier if I'm on holiday.

> Wish me luck :)

Good luck! Thanks for the fixes! :)

**Closed** 2024-08-21 09:46 UTC
Labels: bug
