### ISSUE TITLE
mineways crash on this map

### ISSUE THREAD

**Issue by ouabout** [erich666/Mineways#102] opened 2022-11-09 17:28 UTC
I have downloaded the latest version of minways. It works well most of the time, except this particular map. I have narrowed down the specific region that crashes it no matter what I option I use. 
Selection location: -150, 60, -500 to -101, 255, -451

The problematic map can be downloaded here: https://drive.google.com/file/d/1PfyM0nCHU_obwHTXqA3kx3S8ecK3SK34/view?usp=share_link
I have included the script that would try to export the region in question.

Thanks

**Comment by erich666** [comment] 2022-12-19 17:45
My apologies for the delay in replying - I just noticed this today (I really need to figure out why Github is not alerting me to new issues). Thanks for the excellent reproduction steps and data (I've got the world, so you can remove from share if you like).

I gave it a look and I'm still getting the problem on 10.05, the latest. Notes to self: it has to do with line 10791 in ObjFileManip.cpp:

neighborIndex = boxIndex + gFaceOffset[(stairs[stepDir].sideDir[(neighborDataVal & 0x3)] + 3) % 6];

Something about looking at the neighboring stair step so as to determine what this stair should look like.

The neighborIndex comes out negative, so is accessing something that isn't in the array. I should test for that and recover gracefully. I also need to figure out why it's got a negative index here - it really should not.

I hope to take a look at this over the holiday break.

**Comment by erich666** [comment] 2023-01-06 20:07
Whew, [fixed it](https://github.com/erich666/Mineways/commit/c9c7a827fa95dfb00614999972878122e0d38ece)! And boy is the old stair neighbor code squirrelly. This bug will be fixed in the next release, 10.06. The results might not be perfect, but at least there's no crash.

The problem is that the way that old 1.12 and before worlds determined what stairs looked like was dependent on neighboring stairs. And in fact you need to take the neighbor of the neighbor of a stairs block to truly determine how the stairs block looks like, from what I can tell (or at least, that's what my code does). However, if your stairs block is right on the edge of the exported area, I store only the "hidden" neighboring edge blocks 1 block out from this area, not 2 blocks out. What was happening is that the code was trying to look two blocks out and trying to access data that simply wasn't there, causing a crash.

The cheap fix: carefully check if we're about to try to get a neighbor further outside, in an area we don't have any data for. If so, then quit instead of trying to access non-existent data. We return a "stair mask" (which shows what blocks are visible) of 0x0, which is illegal (and signals "we don't know what's going on with this neighboring stair") and will cause the code to simply continue. Stairs at the very edges like this may fail to render exactly right. It'd be a lot more tedious work to carefully understand this old format and how to recover in a better way. The results look about right, as-is.

A more reliable way to work around the problem is to convert 1.12 and earlier worlds to 1.13 or later. The new 1.13 format does not have this same bug, being able to more locally know how a step is stored - see getStairMask().

**Closed by erich666** 2023-01-06 20:07 UTC
