### ISSUE TITLE
barely any levels underground

### ISSUE THREAD

**Issue by ender-guardian** [erich666/Mineways#113] opened 2023-08-10 15:46 UTC
even if i set the height to the lowest possible, there is still barely anything underground, i rendered a world with mineways that had a deep cave in it, and when i went into it on blender there was barely any of it left, it reached the ground and disappeared at a very high level

**Comment by erich666** [comment] 2023-08-29 14:17
When exporting you need to set the lower Depth (not Height) to capture the cave system you want:

![image](https://github.com/erich666/Mineways/assets/803995/7ab1880a-0ba8-4f4c-b5b0-de85a9d1cfc1)

By default, Mineways looks at whatever you select and chooses this Depth value for you. Mineways finds the lowest block visible from above.

If you have indeed set the Depth to as low as possible (0 or -64 or whatever) and your underground area is not showing up, please zip up the world and send it to me for examination - I'm at erich@acm.org. The Minecraft world format has a flaw in that it doesn't have any global value stored for what the deepest depth is in a world. Mineways does a number of things when a world is loaded to check if any visible chunks are deeper than expected and adjusts this minimum depth accordingly. However, this system isn't perfect. If you're having a problem with a particular world, I'd like to see it and figure out why this is happening.

**Comment by erich666** [comment] 2023-08-29 14:27
Underground export definitely works, e.g.
![image](https://github.com/erich666/Mineways/assets/803995/564894ea-1e17-4044-8e66-51774f8e296d)

**Comment by ender-guardian** [comment] 2023-09-05 18:11
I'm not sure if this is what happened but I will definitely check thank you
loads!!!

**Comment by erich666** [comment] 2023-09-13 14:26
Thanks, and I look forward to hearing how it goes, since I can't reproduce it here.

**Comment by erich666** [comment] 2023-12-31 17:04
Closing, though I still hope for a response, @ender-guardian

**Closed by erich666** 2023-12-31 17:04 UTC
Labels: question
